### ISSUE TITLE
Example for parameter lists

### ISSUE THREAD

**Issue by christianTF** [Tadly/kodi-rpc#1]
Hello tadly,

I've included your kodi-rpc wrapper to my Kodi plugin for LoxBerry (https://github.com/christianTF/LoxBerry-Plugin-Kodi).

Is the kodi-rpc wrapper capable of parameter arrays like this query?

```json
{
   "jsonrpc": "2.0", "method": "Player.GetItem", 
   "params": { 
      "properties": 
          ["title", "album", "artist", "season", "episode", "duration", "showtitle", "tvshowid", "thumbnail", "file", "fanart", "streamdetails"], 
        "playerid": 1 }, 
   "id": "VideoGetItem"}
```
This is only an example of what I mean.
The query sends a list of strings in the properties item.

I simply ask to know if this works, and if yes, how to use it. 

Thanks!
Christian

**Comment by tadly** [comment]
Fearfully I awaited this day...

No, sadly there isn't right now.
Back than I couldn't come up with a nice way of handling this from the cli interface.

They only way I could think of making this case work right now is to have a interface like:
```sh
kodi-rpc -H localhost -P 8080 Player.GetItem properties '["title", "album"]' playerid active
```
That shouldn't be to difficult of a change. I'm not sure if I like it though.

I'll do some more thinking. If you have any ideas, let me know.

**Comment by tadly** [comment]
I added support for it as shown previously with 2ffe499d09a3b4dc154cea4a53a255382d7fc181

**Comment by christianTF** [comment]
:-)

Wow, cool!
You're faster in implementing than I am on writing :-)

I will take the new version, and will watch your repo!

Thanks a lot! 
Christian
