### ISSUE TITLE
Application.GetProperties not working 

### ISSUE THREAD

**Issue by camcs1** [Tadly/kodi-rpc#2]
Hi I am currently trying to write a script to check  if the video player is active. 
I'm using this code
`{"jsonrpc":"2.0","id":1,"method":"Player.GetProperties","params":{ "playerid":1,"properties":["speed"] } }`
This works in browser but I can't seem to get it to work with your script.  

This is how I have formatted it:
`Application.GetProperties properties '[speed]' player id active`

And this is the error I get:
`{"error":{"code": -32700, "message":"parse error."},"id":null,"jsonrpc":"2.0"}`

Any help would be appreciated and I hope I'm not just being a noob,
Thanks Cam

**Comment by christianTF** [comment]
You need double-Quotes `"speed"`

**Comment by tadly** [comment]
1. in the first request you use `Player.GetProperties` while in the second you use `Application.GetProperties`
2. it's `playerid` not `player id`
3. what @christianTF said

so what you want is:
`Player.GetProperties properties '["speed"]' playerid active`

Hope you can manage from here :)

**Comment by camcs1** [comment]
Thanks that solved it for me, had to be something noobish....
